spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SPRING_JPA_SHOW_SQL}
    hibernate.ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}

fxgames:
  limit: ${FXGAMES_LIMIT_RECORD_MEASSAGE_BYTE}